name: pyshbundle-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - netCDF4
  - xarray
  - geopandas
  - cartopy
  - rasterio
  - shapely
  - tqdm
  - rioxarray
  - pytest
  - pytest-cov
  - pip
  - pip:
    - julian